helm-extra-args: --timeout 600s
check-version-increment: false
debug: true
chart-dirs:
  - helm
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
charts: [ "helm/hawkbit-operator" ] # need to prefix with "helm/"
namespace: "hawkbit-operator-ci"
release-label: "app.kubernetes.io/instance" # required because of "namespace"
target-branch: main