apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: client-secret
  labels:
    app: sso
    keycloak: hawkbit
    realm: hawkbit
    client: hawkbit
spec:
  client:
    enabled: true
    clientAuthenticatorType: client-secret
    redirectUris:
      - 'https://default-hawkbit-operator.apps.wonderful.iot-playground.org/'
      - 'https://default-hawkbit-operator.apps.wonderful.iot-playground.org/login/oauth2/code/hawkbit-client'
    clientId: client-secret
    rootUrl: 'https://default-hawkbit-operator.apps.wonderful.iot-playground.org/'
    implicitFlowEnabled: false
    secret: client-secret
    publicClient: false
    standardFlowEnabled: true
    defaultRoles:
      - system_admin

      - create_target
      - read_target
      - read_target_security_token
      - update_target
      - delete_target

      - create_repository
      - read_repository
      - update_repository
      - delete_repository

      - download_repository_artifact
      - tenant_configuration

      - create_rollout
      - read_rollout
      - update_rollout
      - delete_rollout
      - handle_rollout
      - approve_rollout

    directAccessGrantsEnabled: false
  realmSelector:
    matchLabels:
      app: sso
      keycloak: hawkbit
      realm: hawkbit
