kind: Hawkbit
apiVersion: iot.eclipse.org/v1alpha1
metadata:
  name: default
spec:
  imageOverrides:
    hawkbit-update-server:
      image: docker.io/ctron/hawkbit-update-server:latest
      pullPolicy: Always
  database:
    mysql:
      database: hawkbit
      host: hawkbit-db-mysql
      username: hawkbit
      passwordSecret:
        name: hawkbit-db-mysql
        field: mysql-password
  rabbit:
    host: hawkbit-rabbit-rabbitmq
    username: hawkbit
    passwordSecret:
      name: hawkbit-rabbit-rabbitmq
      field: rabbitmq-password
