name: ci

on: [push, pull_request]

env:
  IMAGE_NAME: hawkbit-operator

jobs:

  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history for chart testing
        run: git fetch --prune --unshallow
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: .github/ct.yaml

  build:
    name: build
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          name: binary
          path: target/release/hawkbit-operator

      - run: ls target/release/

      - name: Build container
        run: |
          docker build . --file .github/Dockerfile \
            --tag $IMAGE_NAME

      - name: Login to github container repository
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push latest to github container repository
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "$default-branch" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=ci

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - build
    strategy:
      matrix:
        k8s:
          # the versions supported by chart-testing are the tags
          # available for the docker.io/kindest/node image
          # https://hub.docker.com/r/kindest/node/tags
          - v1.14.10
          - v1.15.11
          - v1.16.9
          - v1.17.5
          - v1.18.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history for chart testing
        run: git fetch --prune --unshallow

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.0.0
        with:
          config: .github/kind-config.yaml
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Pre-create namespace
        run: kubectl create namespace hawkbit-operator-ci

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: .github/ct.yaml