---
{{- if .Values.rbac.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hawkbit-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hawkbit-operator.name" . }}
{{ include "hawkbit-operator.labels" . | indent 4 }}
roleRef:
  kind: Role
  name: {{ include "hawkbit-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "hawkbit-operator.serviceAccountName" . }}
{{- end -}}
