---
{{- if .Values.rbac.enabled -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hawkbit-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hawkbit-operator.name" . }}
{{ include "hawkbit-operator.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "services", "configmaps", "secrets", "serviceaccounts", "persistentvolumeclaims"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets" ]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
  - apiGroups: ["keycloak.org"]
    resources: ["keycloaks", "keycloakrealms", "keycloakclients", "keycloakusers"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
  - apiGroups: ["iot.eclipse.org"]
    resources: ["hawkbits", "hawkbits/status", "hawkbits/finalizers"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
{{- end -}}
